### ISSUE TITLE
Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = 0.0.0.0, port = 1900

### ISSUE THREAD

**Issue by iptodays** [suconghou/dlna-dart#2]
非常感谢作者提供的插件，开始搜索的时候遇到了下面的问题

设备: iPhone Xs Max
系统版本: 14.7.1
Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = 0.0.0.0, port = 1900
![image](https://user-images.githubusercontent.com/15830996/130929499-d486b0bf-8609-496c-8d87-bb2fc3a857cc.png)

**Comment by nicaho** [comment]
我发现在iOS17.5以上的iOS设备，会继续报这个错误。其他iOS系统以及安卓系统是正常的。

以下是我的flutter --version信息
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (1 year, 3 months ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by suconghou** [comment]
你的flutter版本比较旧，升级到 3.22 试试呢

**Comment by nicaho** [comment]
我们其他第三方库要依赖Flutter 3.7.12，如果要更新，也会涉及到其他库的更新。最新版在iOS17.5是没问题的，对吗

**Comment by suconghou** [comment]
这个问题源自于dart里的问题， 参考 https://github.com/dart-lang/sdk/issues/42250
最新版在iOS17.5有没有问题，我也不确定，但是之前已经按照dart官方的修复方式绕过了，其他用户也反馈没有问题了。
如果你仍然遇到问题，请确认其他服务没有占用此端口，开启服务时 使用 start(reusePort:true)

**Comment by nicaho** [comment]
我更新到最新版本，然后新建一个项目跑搜索设备
Flutter版本信息：flutter --version                       
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (5 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

iPhone信息：iPhone15 Pro，iOS17.5.1

搜索设备时：searcher.start(reusePort: true) 
报错信息：[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: OS Error: Address already in use, errno = 48
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1790:74)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1680:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2661:56)
#3      DLNAManager.start (package:dlna_dart/dlna.dart:527:25)


另外，此端口，是指哪个端口
![image](https://github.com/suconghou/dlna-dart/assets/5061802/b29abc23-aff2-457f-b04a-cc7491038517)
是对应的1900吗
