### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by aluedtke7** [suconghou/dlna-dart#4]
Hi,

I'm trying to play audio files from a MiniDLNA server locally on an Android phone.

So far, I can search for DLNA server in my network and I get the MiniDLNA device. But when I try to access this device I get always the error "Bad state: No element".

I tried to figure out what your u2flutter is doing, but it's really hard for a non chinese speaking person like me. I did see here in another issue that someone else was mentioning this error too. But since that conversation is also in chinese, it didn't helped me.

Maybe you can give me some advise how to grab artists, albums and songs from the DLNA server using your library.

Thanks

**Comment by suconghou** [comment]
MiniDLNA works as a MediaServer not a MediaRender , while this library is used to communicate with a MediaRender and cast any playable url to the MediaRender , eg : TV ; to work with MediaServer , we need implement the ContentDirectory service, which is not implemented now , we may implement it in the next fews weeks if it is necessary

**Comment by aluedtke7** [comment]
Thank you for the fast and clarifying answer.
