### ISSUE TITLE
升级flutter3.x

### ISSUE THREAD

**Issue by yi-boide** [suconghou/dlna-dart#8]
问下，是否有升级flutter3.x的计划，让其支持flutter3.x中使用

**Comment by yi-boide** [comment]
运行的这个例子u2flutter中，点开播放视频，右上角的功能无法使用，会整体页面刷一下，然后没任何反应，（投屏助手/收藏此视频/收藏此频道）

**Comment by suconghou** [comment]
这个应该是u2flutter里的渲染菜单的bug，不是本项目里的
